language: go
go:
    - 1.3
    - 1.4
    - 1.5
    - tip
install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
notifications:
    email:
        on_success: change
        on_failure: always
    slack: marshland:whhps9g7T0jujrU9PCK3ojGP
