language: go
go:
    - 1.3
    - 1.4
    - 1.5
    - tip
install:
    - go get golang.org/x/tools/cmd/cover
script:
    - go test -v -covermode=atomic -coverprofile=coverage.txt
after_success:
    - bash <(curl -s https://codecov.io/bash)
notifications:
    email:
        on_success: change
        on_failure: always
    slack: marshland:whhps9g7T0jujrU9PCK3ojGP
