version: '{build}'
clone_folder: C:\gopath\src\github.com\bolsote\autoconfig.go
init:
- ps: >-
    Get-ChildItem Env:

    go version

    go env
environment:
  GOPATH: C:\gopath
install:
- ps: go get golang.org/x/tools/cmd/cover
build_script:
- ps: go build
test_script:
- ps: go test -v
notifications:
- provider: Slack
  auth_token:
    secure: BZ6OaiiHNRfyqiHWRyzuMrK0YfZVVSG/Uf1QIRW+rBV1yEVHaPrSq9L2YUyDYPtKnAurnOGjoKyD3MEmIG5w4Q==
  channel: build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
